#ifndef _BIT_MATH_H_
#define _BIT_MATH_H_


#define SET_BIT(REGISTER,BIT_NO) (REGISTER|=(1<<BIT_NO))
#define CLR_BIT(REGISTER,BIT_NO) (REGISTER&=~(1<<BIT_NO))
#define TOG_BIT(REGISTER,BIT_NO) (REGISTER^=(1<<BIT_NO))
#define GET_BIT(REGISTER,BIT_NO) ((REGISTER>>BIT_NO)&1)
#define ASSIGN_BIT(REGISTER,BIT_NO,value) REGISTER=((REGISTER&(~(1<<BIT_NO)))|(val<<BIT_NO)

#endif
